-- MySQL Script generated by MySQL Workbench
-- Tue May 20 12:56:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`ubicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ubicaciones` (
  `id_ubicacion` INT NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(70) NOT NULL,
  `pais` VARCHAR(50) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_ubicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`aeropuertos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aeropuertos` (
  `id_aeropuerto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo_iata` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `id_ubicacion` INT NOT NULL,
  PRIMARY KEY (`id_aeropuerto`, `id_ubicacion`),
  INDEX `fk_aeropuertos_ubicaciones_idx` (`id_ubicacion` ASC) VISIBLE,
  CONSTRAINT `fk_aeropuertos_ubicaciones`
    FOREIGN KEY (`id_ubicacion`)
    REFERENCES `mydb`.`ubicaciones` (`id_ubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vuelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vuelos` (
  `id_vuelo` INT NOT NULL AUTO_INCREMENT,
  `numero_vuelo` VARCHAR(45) NOT NULL,
  `aerolinea` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `aeropuertos_id_aeropuertos` INT NOT NULL,
  `aeropuertos_id_ubicacion` INT NOT NULL,
  PRIMARY KEY (`id_vuelo`, `aeropuertos_id_aeropuertos`, `aeropuertos_id_ubicacion`),
  INDEX `fk_vuelos_aeropuertos1_idx` (`aeropuertos_id_aeropuertos` ASC, `aeropuertos_id_ubicacion` ASC) VISIBLE,
  CONSTRAINT `fk_vuelos_aeropuertos1`
    FOREIGN KEY (`aeropuertos_id_aeropuertos` , `aeropuertos_id_ubicacion`)
    REFERENCES `mydb`.`aeropuertos` (`id_aeropuerto` , `id_ubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vuelos_programados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vuelos_programados` (
  `id_vuelo_programado` INT NOT NULL AUTO_INCREMENT,
  `id_vuelo` INT NOT NULL,
  `fecha_hora_salida` DATETIME NOT NULL,
  `fecha_hora_llegada` DATETIME NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_vuelo_programado`, `id_vuelo`),
  INDEX `fk_vuelos_programados_vuelos1_idx` (`id_vuelo` ASC) VISIBLE,
  CONSTRAINT `fk_vuelos_programados_vuelos1`
    FOREIGN KEY (`id_vuelo`)
    REFERENCES `mydb`.`vuelos` (`id_vuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`escalas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`escalas` (
  `id_escala` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora_llegada` DATETIME NOT NULL,
  `fecha_hora_salida` DATETIME NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `id_aeropuertos` INT NOT NULL,
  `vuelos_programados_id_vuelos_programados` INT NOT NULL,
  `vuelos_programados_vuelos_id_vuelo` INT NOT NULL,
  `vuelos_programados_vuelos_aeropuertos_id_aeropuertos` INT NOT NULL,
  `vuelos_programados_vuelos_aeropuertos_id_ubicacion` INT NOT NULL,
  PRIMARY KEY (`id_escala`, `id_aeropuertos`, `vuelos_programados_id_vuelos_programados`, `vuelos_programados_vuelos_id_vuelo`, `vuelos_programados_vuelos_aeropuertos_id_aeropuertos`, `vuelos_programados_vuelos_aeropuertos_id_ubicacion`),
  INDEX `fk_escalas_aeropuertos1_idx` (`id_aeropuertos` ASC) VISIBLE,
  INDEX `fk_escalas_vuelos_programados1_idx` (`vuelos_programados_id_vuelos_programados` ASC, `vuelos_programados_vuelos_id_vuelo` ASC, `vuelos_programados_vuelos_aeropuertos_id_aeropuertos` ASC, `vuelos_programados_vuelos_aeropuertos_id_ubicacion` ASC) VISIBLE,
  CONSTRAINT `fk_escalas_aeropuertos1`
    FOREIGN KEY (`id_aeropuertos`)
    REFERENCES `mydb`.`aeropuertos` (`id_aeropuerto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escalas_vuelos_programados1`
    FOREIGN KEY (`vuelos_programados_id_vuelos_programados` , `vuelos_programados_vuelos_id_vuelo`)
    REFERENCES `mydb`.`vuelos_programados` (`id_vuelo_programado` , `id_vuelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_tipo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `id_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_tipo_usuario`),
  INDEX `fk_usuarios_tipo_usuario1_idx` (`id_tipo_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_tipo_usuario1`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `mydb`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_reserva` (
  `id_estado_reserva` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_estado_reserva`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservas` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `fecha_hora_reserva` DATETIME NOT NULL,
  `cantidad_pasajeros` INT NOT NULL,
  `costo_total` INT NOT NULL,
  `id_estado_reserva` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_reserva`, `id_estado_reserva`, `id_usuario`),
  INDEX `fk_reservas_usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_reservas_estado_reserva1_idx` (`id_estado_reserva` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_estado_reserva1`
    FOREIGN KEY (`id_estado_reserva`)
    REFERENCES `mydb`.`estado_reserva` (`id_estado_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reservas_vuelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reservas_vuelos` (
  `id_reserva_vuelo` INT NOT NULL AUTO_INCREMENT,
  `id_vuelos_programados` INT NOT NULL,
  `id_reservas` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_reserva_vuelo`, `id_vuelos_programados`, `id_reservas`),
  INDEX `fk_reservas_vuelos_vuelos_programados1_idx` (`id_vuelos_programados` ASC) VISIBLE,
  INDEX `fk_reservas_vuelos_reservas1_idx` (`id_reservas` ASC) VISIBLE,
  CONSTRAINT `fk_reservas_vuelos_vuelos_programados1`
    FOREIGN KEY (`id_vuelos_programados`)
    REFERENCES `mydb`.`vuelos_programados` (`id_vuelo_programado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservas_vuelos_reservas1`
    FOREIGN KEY (`id_reservas`)
    REFERENCES `mydb`.`reservas` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_asiento` (
  `id_estado_asiento` INT NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_estado_asiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clase_asiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clase_asiento` (
  `id_clase_asiento` INT NOT NULL,
  `tipo_clase` VARCHAR(50) NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_clase_asiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`asientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`asientos` (
  `id_asientos` INT NOT NULL AUTO_INCREMENT,
  `numero_asiento` INT NOT NULL,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` TINYINT NULL,
  `id_usuario` INT NULL,
  `id_reserva` INT NOT NULL,
  `id_estado_asiento` INT NOT NULL,
  `id_clase_asiento` INT NOT NULL,
  PRIMARY KEY (`id_asientos`, `id_reserva`, `id_estado_asiento`, `id_clase_asiento`),
  INDEX `fk_asientos_reservas1_idx` (`id_reserva` ASC) VISIBLE,
  INDEX `fk_asientos_estado_asiento1_idx` (`id_estado_asiento` ASC) VISIBLE,
  INDEX `fk_asientos_clase_asiento1_idx` (`id_clase_asiento` ASC) VISIBLE,
  CONSTRAINT `fk_asientos_reservas1`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `mydb`.`reservas` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asientos_estado_asiento1`
    FOREIGN KEY (`id_estado_asiento`)
    REFERENCES `mydb`.`estado_asiento` (`id_estado_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asientos_clase_asiento1`
    FOREIGN KEY (`id_clase_asiento`)
    REFERENCES `mydb`.`clase_asiento` (`id_clase_asiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
