-- MySQL Script generated by MySQL Workbench
-- Wed Mar 12 12:55:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_Usuario` (
  `idtipo_Usuario` INT NOT NULL AUTO_INCREMENT,
  `type_nameUser` VARCHAR(45) NOT NULL,
  `description_tipo` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idtipo_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios` (
  `id_Usuarios` INT NOT NULL AUTO_INCREMENT,
  `nombre_Usuario` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `Phone` VARCHAR(15) NULL,
  `id_tipoUser` INT NOT NULL,
  PRIMARY KEY (`id_Usuarios`, `id_tipoUser`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC) VISIBLE,
  UNIQUE INDEX `Phone_UNIQUE` (`Phone` ASC) VISIBLE,
  INDEX `fk_Usuarios_tipo_Usuario_idx` (`id_tipoUser` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_tipo_Usuario`
    FOREIGN KEY (`id_tipoUser`)
    REFERENCES `mydb`.`tipo_Usuario` (`idtipo_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
